import fetch from "node-fetch";
import { writeFileSync } from "fs";

const LANG_CODE_URL =
  "https://cloud.google.com/speech-to-text/docs/common/languages.json";

type FixedArray<T, L extends number> = [T, ...T[]] & { length: L };

type ColumnLength = 8;

type Titles = FixedArray<Title, ColumnLength>;

type Record = FixedArray<string, ColumnLength>;

type Data = [Titles, ...Record[]];

interface Title {
  label: string;
  value: string;
}

const main = async () => {
  const response = await fetch(LANG_CODE_URL);
  const data = (await response.json()) as Data;
  const records = data.slice(1) as Record[];
  const codes = records.map(record => record[1]);
  const str = JSON.stringify(codes)
    .replace(/(\[|\])/g, "")
    .replace(/,/g, "|");
  const text = `// Do not edit directly. Generated by scripts/ts/languageCodes/index.ts
  type languageCodes = ${str};
  export default languageCodes;`;
  writeFileSync("./scripts/ts/languageCode/LanguageCode.ts", text);
};

main().catch(console.error);
